INSERT INTO carriers (name, slug, country, api_available, scrape_available, tracking_url_template) VALUES
    ('USPS', 'usps', 'US', true, true, 'https://tools.usps.com/go/TrackConfirmAction?tLabels={tracking_number}'),
    ('UPS', 'ups', 'US', true, true, 'https://www.ups.com/track?tracknum={tracking_number}'),
    ('FedEx', 'fedex', 'US', true, true, 'https://www.fedex.com/fedextrack/?trknbr={tracking_number}'),
    ('DHL Express', 'dhl-express', 'DE', true, true, 'https://www.dhl.com/en/express/tracking.html?AWB={tracking_number}'),
    ('Royal Mail', 'royal-mail', 'GB', false, true, 'https://www.royalmail.com/track-your-item#/tracking-results/{tracking_number}'),
    ('Canada Post', 'canada-post', 'CA', false, true, 'https://www.canadapost-postescanada.ca/track-reperage/en#/tracking/{tracking_number}'),
    ('Australia Post', 'australia-post', 'AU', false, true, 'https://auspost.com.au/mypost/track/#/details/{tracking_number}'),
    ('Deutsche Post', 'deutsche-post', 'DE', false, true, 'https://www.deutschepost.de/en/p/track.html?piececode={tracking_number}'),
    ('DHL Parcel DE', 'dhl-parcel-de', 'DE', false, true, 'https://www.dhl.de/en/privatkunden/pakete-empfangen/verfolgung.html?piececode={tracking_number}'),
    ('GLS', 'gls', 'DE', false, true, 'https://gls-group.eu/en/track/{tracking_number}'),
    ('Hermes', 'hermes', 'DE', false, true, 'https://www.myhermes.de/tracking?tracking={tracking_number}'),
    ('Yanwen', 'yanwen', 'CN', false, true, 'https://track.yw56.com.cn/en/detail?number={tracking_number}'),
    ('China Post', 'china-post', 'CN', false, true, 'http://tracking.chinapost.com/track/{tracking_number}'),
    ('Japan Post', 'japan-post', 'JP', false, true, 'https://trackings.post.japanpost.jp/en/delivery/{tracking_number}'),
    ('India Post', 'india-post', 'IN', false, true, 'https://www.indiapost.gov.in/vas/Pages/track/{tracking_number}'),
    ('Correos (Spain)', 'correos', 'ES', false, true, 'https://www.correos.es/en/track/{tracking_number}'),
    ('Poste Italiane', 'poste-italiane', 'IT', false, true, 'https://www.poste.it/track/{tracking_number}'),
    ('La Poste (France)', 'la-poste', 'FR', false, true, 'https://www.laposte.fr/outils/suivre-vos-envois?code={tracking_number}'),
    ('PostNord', 'postnord', 'SE', false, true, 'https://www.postnord.com/en/track-and-trace/?shipmentId={tracking_number}'),
    ('Swiss Post', 'swiss-post', 'CH', false, true, 'https://www.post.ch/en/track/{tracking_number}'),
    ('An Post (Ireland)', 'an-post', 'IE', false, true, 'https://track.anpost.ie/Tracking/{tracking_number}'),
    ('New Zealand Post', 'nz-post', 'NZ', false, true, 'https://www.nzpost.co.nz/tools/track?trackid={tracking_number}'),
    ('Singapore Post', 'singapore-post', 'SG', false, true, 'https://www.singpost.com/track/{tracking_number}'),
    ('Pos Malaysia', 'pos-malaysia', 'MY', false, true, 'https://www.poslaju.com.my/track/{tracking_number}'),
    ('Thai Post', 'thai-post', 'TH', false, true, 'https://track.thailandpost.co.th/{tracking_number}')
ON CONFLICT (slug) DO NOTHING;
